In [1]:
 
import numpy as np
import tensorflow as tf
import matplotlib.pyplot as plt
from sklearn.linear_model import Perceptron
from sklearn.datasets import make_classification
from sklearn.neural_network import MLPClassifier



In [2]:


class ARTNeuralNetwork:
    def __init__(self, num_features, max_categories=100, rho=0.5, beta=1.0):
        self.num_features = num_features
        self.max_categories = max_categories
        self.rho = rho
        self.beta = beta

        self.categories = np.ones((max_categories, num_features))

    def compute_similarity(self, pattern):
        return np.sum(self.categories * pattern, axis=1) / (self.beta + np.sum(self.categories, axis=1))

    def learn(self, patterns):
        for p in patterns:
            pattern = np.array(p)
            while True:
                similarity = self.compute_similarity(pattern)
                if np.max(similarity) < self.rho:
                    # If no category is similar enough, create a new one
                    self.categories = np.vstack((self.categories, pattern))
                    break
                else:
                    # Update the most similar category
                    winner = np.argmax(similarity)
                    self.categories[winner] = self.beta * self.categories[winner] + (1 - self.beta) * pattern
                    if np.sum(self.categories[winner]) / np.sum(pattern) >= self.rho:
                        break
                    else:
                        self.categories = np.delete(self.categories, (winner), axis=0)
        return self.categories

    def predict(self, patterns):
        predictions = []
        for p in patterns:
            pattern = np.array(p)
            similarity = self.compute_similarity(pattern)
            winner = np.argmax(similarity)
            predictions.append(winner)
        return predictions

 

In [4]:
 


        
# Define binary patterns
patterns = [
    [1, 0, 0, 1, 1],
    [1, 0, 0, 1, 0],
    [0, 1, 1, 0, 0],
    [0, 0, 1, 1, 0],
]

# Initialize ART1 network
art1 = ARTNeuralNetwork(num_features=5, max_categories=4, rho=0.6, beta=0.5)

# Learn patterns
categories = art1.learn(patterns)
print(f"Categories after learning: {categories}")

# Predict categories for patterns
predictions = art1.predict(patterns)
print(f"Predicted categories: {predictions}")


Categories after learning: [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 0. 0. 1. 1.]
 [1. 0. 0. 1. 0.]
 [0. 1. 1. 0. 0.]
 [0. 0. 1. 1. 0.]]
Predicted categories: [4, 5, 6, 7]
